services:
  # Сервис базы данных
  db:
    image: postgres:15
    container_name: taxi_postgres
    restart: always
    environment:
      POSTGRES_USER: fox
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: ny_taxi
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Твой ETL-пайплайн
  spark_app:
    build: .
    container_name: taxi_pipeline_container
    depends_on:
      - db
    #volumes:
      #- ./data:/app/data
      #- ./src:/app/src    # <--- FOR TEST!
    env_file:
      - .env
      
  # airflow
  airflow:
    image: apache/airflow:2.8.1
    container_name: taxi_airflow
    user: root  # Права администратора для доступа к ядру Докера
    ports:
      - "8080:8080"  # Веб-интерфейс будет доступен в браузере по этому порту
    volumes:
      - ./dags:/opt/airflow/dags
      - /var/run/docker.sock:/var/run/docker.sock  # Щупальце к ядру Докера
      - ./:/opt/airflow/project  # Даем Airflow доступ к файлам твоего проекта
    env_file:
      - .env
    command: >
      bash -c "
      apt-get update && apt-get install -y docker.io curl &&
      curl -L 'https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-linux-x86_64' -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose &&
      airflow db migrate &&
      airflow users create --username admin --password admin --firstname Fox --lastname Admin --role Admin --email fox@example.com &&
      cd /opt/airflow/project &&
      airflow standalone
      "
volumes:
  pgdata: